import type { Metadata } from "next";
import "aos/dist/aos.css";
import "./globals.css";
import { lexend } from "@/utils/fonts";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "MFM WebTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <div className="bg"></div>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
